# Generated by Django 2.2.7 on 2019-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('userpw', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('level_point', models.IntegerField()),
                ('level', models.IntegerField()),
                ('item_top', models.IntegerField()),
                ('item_bottom', models.IntegerField()),
                ('item_shoes', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
        ),
    ]
