# Generated by Django 2.2.7 on 2019-11-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipdrobe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate1',
            fields=[
                ('cate1', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cate1_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='item_bottom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='item_shoes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='item_top',
        ),
        migrations.AddField(
            model_name='user',
            name='count_bottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_shoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='count_top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate1_name', models.CharField(max_length=20)),
                ('cate2_name', models.CharField(max_length=20)),
                ('part', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=40, null=True)),
                ('solid', models.BooleanField(null=True)),
                ('pattern', models.CharField(max_length=15, null=True)),
                ('season', models.CharField(max_length=30, null=True)),
                ('descript', models.CharField(max_length=100, null=True)),
                ('worn', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('texture', models.CharField(max_length=15, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate2', models.CharField(max_length=20)),
                ('cate2_name', models.CharField(max_length=20)),
                ('worn', models.IntegerField(default=0)),
                ('cate1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.Cate1')),
            ],
        ),
        migrations.AddField(
            model_name='cate1',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.Part'),
        ),
    ]
