# Generated by Django 2.2.8 on 2019-12-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hipdrobe', '0003_auto_20191127_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('elem_list', models.TextField()),
                ('is_daily', models.BooleanField()),
                ('bg_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.User')),
            ],
        ),
    ]
