# Generated by Django 2.2.8 on 2019-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hipdrobe', '0004_coordi'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordi',
            name='wear_at',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
